name: PHP Composer

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        operating-system: [ ubuntu-20.04 ]
        php: [ '7.4' ]
    name: PHP ${{ matrix.php }} sample
    steps:
      - uses: actions/checkout@master
      - run: cp index.php  /var/www/html/index.php